pub const DEFAULT_CONFIG_DIR: &str = "~/.config/omah";
pub const DEFAULT_CONFIG_FILE: &str = "omah-config.toml";
pub const DEFAULT_VAULT_PATH: &str = "~/.config/omah/vault";
/// Package name → binary name mapping for packages whose installed binary
/// differs from the package name. Lookup is case-insensitive.
///
/// Format: `("package-name", "binary-name")` — multiple package aliases may
/// map to the same binary (add them as separate entries).
pub const PKG_TO_BIN: &[(&str, &str)] = &[
    // ── Editors ──────────────────────────────────────────────────────────────
    ("neovim", "nvim"),
    ("vim-nox", "vim"),
    ("gvim", "vim"),
    ("emacs-nox", "emacs"),
    ("emacs-gtk", "emacs"),
    ("code", "code"), // VS Code (snap/apt name)
    ("visual-studio-code", "code"),
    ("helix", "hx"),
    ("micro-editor", "micro"),
    ("kakoune", "kak"),
    // ── Search / file tools ──────────────────────────────────────────────────
    ("ripgrep", "rg"),
    ("fd-find", "fd"), // Debian/Ubuntu apt name
    ("fd-rs", "fd"),
    ("bat-cat", "bat"), // some distros
    ("the_silver_searcher", "ag"),
    ("silversearcher-ag", "ag"), // Debian apt name
    ("ugrep", "ugrep"),
    ("hypergrep", "hgrep"),
    ("fzf", "fzf"),
    ("skim", "sk"),
    ("broot", "br"),
    ("lsd", "lsd"),
    ("eza", "eza"),
    ("exa", "eza"), // deprecated alias
    ("tre-command", "tre"),
    ("dust", "dust"),
    ("dua-cli", "dua"),
    ("ncdu", "ncdu"),
    ("tokei", "tokei"),
    ("loc", "loc"),
    // ── Shell & navigation ───────────────────────────────────────────────────
    ("nushell", "nu"),
    ("zoxide", "zoxide"),
    ("fish", "fish"),
    ("zsh", "zsh"),
    ("bash", "bash"),
    ("dash", "dash"),
    ("elvish", "elvish"),
    ("xonsh", "xonsh"),
    ("oil-shell", "osh"),
    ("carapace-bin", "carapace"),
    ("atuin", "atuin"),
    ("mcfly", "mcfly"),
    ("direnv", "direnv"),
    ("starship", "starship"),
    ("oh-my-posh", "oh-my-posh"),
    // ── Terminal multiplexers ─────────────────────────────────────────────────
    ("tmux", "tmux"),
    ("zellij", "zellij"),
    ("screen", "screen"),
    ("byobu", "byobu"),
    // ── TUI system tools ──────────────────────────────────────────────────────
    ("bottom", "btm"),
    ("btop", "btop"),
    ("htop", "htop"),
    ("gtop", "gtop"),
    ("glances", "glances"),
    ("procs", "procs"),
    ("bandwhich", "bandwhich"),
    ("nethogs", "nethogs"),
    ("iftop", "iftop"),
    ("gping", "gping"),
    ("dog", "dog"),
    ("xh", "xh"),
    ("curlie", "curlie"),
    ("httpie", "http"), // httpie → http binary
    ("http", "http"),
    // ── Diff / VCS ───────────────────────────────────────────────────────────
    ("difftastic", "difft"),
    ("delta", "delta"),
    ("git-delta", "delta"),
    ("diff-so-fancy", "diff-so-fancy"),
    ("lazygit", "lazygit"),
    ("gitui", "gitui"),
    ("tig", "tig"),
    ("gh", "gh"),     // GitHub CLI
    ("glab", "glab"), // GitLab CLI
    ("hub", "hub"),
    // ── Language runtimes & package managers ─────────────────────────────────
    ("nodejs", "node"),
    ("node-js", "node"),
    ("nodejs-lts", "node"),
    ("python", "python3"),
    ("python3-pip", "python3"),
    ("python3", "python3"),
    ("pyenv", "pyenv"),
    ("pipx", "pipx"),
    ("poetry", "poetry"),
    ("uv", "uv"),
    ("rye", "rye"),
    ("ruby", "ruby"),
    ("rbenv", "rbenv"),
    ("rvm", "rvm"),
    ("rustup", "rustup"),
    ("cargo", "cargo"),
    ("go", "go"),
    ("golang", "go"),
    ("java", "java"),
    ("openjdk", "java"),
    ("temurin", "java"),
    ("deno", "deno"),
    ("bun", "bun"),
    ("pnpm", "pnpm"),
    ("yarn", "yarn"),
    ("lua", "lua"),
    ("luarocks", "luarocks"),
    ("php", "php"),
    ("composer", "composer"),
    ("perl", "perl"),
    ("elixir", "elixir"),
    ("erlang", "erl"),
    ("erlang-solutions", "erl"),
    ("scala", "scala"),
    ("kotlin", "kotlin"),
    ("swift", "swift"),
    ("dart", "dart"),
    ("flutter", "flutter"),
    ("zig", "zig"),
    ("nim", "nim"),
    ("crystal", "crystal"),
    ("haskell-platform", "ghc"),
    ("ghc", "ghc"),
    ("stack", "stack"),
    ("cabal-install", "cabal"),
    ("ocaml", "ocaml"),
    ("opam", "opam"),
    ("dotnet", "dotnet"),
    ("dotnet-sdk", "dotnet"),
    // ── Build tools ──────────────────────────────────────────────────────────
    ("cmake", "cmake"),
    ("make", "make"),
    ("ninja-build", "ninja"),
    ("ninja", "ninja"),
    ("meson", "meson"),
    ("autoconf", "autoconf"),
    ("automake", "automake"),
    ("pkg-config", "pkg-config"),
    ("pkgconf", "pkg-config"),
    // ── Containers & cloud ───────────────────────────────────────────────────
    ("docker", "docker"),
    ("docker-ce", "docker"),
    ("podman", "podman"),
    ("kubectl", "kubectl"),
    ("kubernetes-cli", "kubectl"), // Homebrew name
    ("helm", "helm"),
    ("k9s", "k9s"),
    ("terraform", "terraform"),
    ("pulumi", "pulumi"),
    ("ansible", "ansible"),
    ("aws-cli", "aws"),
    ("awscli", "aws"),
    ("azure-cli", "az"),
    ("google-cloud-sdk", "gcloud"),
    ("gcloud", "gcloud"),
    ("flyctl", "flyctl"),
    ("wrangler", "wrangler"),
    // ── Fonts / misc ─────────────────────────────────────────────────────────
    ("stow", "stow"),
    ("chezmoi", "chezmoi"),
    ("mackup", "mackup"),
    ("antibody", "antibody"),
    ("antigen", "antigen"),
    ("zinit", "zinit"),
    ("sheldon", "sheldon"),
    ("topgrade", "topgrade"),
    ("mas", "mas"), // Mac App Store CLI
    ("mas-cli", "mas"),
    ("nvm", "nvm"),
];
