/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotfileNameRouteImport } from './routes/dotfile.$name'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotfileNameRoute = DotfileNameRouteImport.update({
  id: '/dotfile/$name',
  path: '/dotfile/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/settings': typeof SettingsRoute
  '/dotfile/$name': typeof DotfileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/settings': typeof SettingsRoute
  '/dotfile/$name': typeof DotfileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/settings': typeof SettingsRoute
  '/dotfile/$name': typeof DotfileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diff' | '/settings' | '/dotfile/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diff' | '/settings' | '/dotfile/$name'
  id: '__root__' | '/' | '/diff' | '/settings' | '/dotfile/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffRoute: typeof DiffRoute
  SettingsRoute: typeof SettingsRoute
  DotfileNameRoute: typeof DotfileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dotfile/$name': {
      id: '/dotfile/$name'
      path: '/dotfile/$name'
      fullPath: '/dotfile/$name'
      preLoaderRoute: typeof DotfileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffRoute: DiffRoute,
  SettingsRoute: SettingsRoute,
  DotfileNameRoute: DotfileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
